theme: jekyll-theme-slate
title: Chapman et al. (2020)
description: Multivariate Visualisation Tutorials
show_downloads: true
github:
  zip_url: https://github.com/brettChapman/multivis_tutorials/archive/master.zip
  tar_url: https://github.com/brettChapman/multivis_tutorials/archive/master.tar.gz
