name: multivis_tutorials
channels:
- defaults
- conda-forge
- brett.chapman
dependencies:
- python=3.6.7
- beakerx=1.3.0
- numpy=1.16.2
- pandas=0.24.2
- openpyxl=2.6.1
- multivis=0.1.7
- tornado=5.1.1
