name: multivis_tutorials
channels:
- defaults
- conda-forge
- brett.chapman
dependencies:
- python>=3.5
- numpy=1.20.2
- pandas=1.2.4
- openpyxl=2.6.1
- multivis=0.5.4
- ipython=7.25.0
- ipykernel=6.0.0
- jupyter-notebook=6.4.0
- jupyter
